name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      db-1:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: test_database
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run backend container
        run: docker run -d --name backend-1 backend-1

      - name: Run frontend container
        run: docker run -d --name frontend-1 frontend-1

      - name: Wait for frontend container to start
        run: sleep 10s

      - name: Check if backend container is running
        run: docker ps | grep backend-1

      - name: Check if frontend container is running
        run: docker ps | grep frontend-1

      # Add steps to run any frontend tests here